{ results: 
   [ { address_components: 
        [ { long_name: 'Samarate',
            short_name: 'Samarate',
            types: [ 'locality', 'political', [length]: 2 ] },
          { long_name: 'Samarate',
            short_name: 'Samarate',
            types: [ 'administrative_area_level_3', 'political', [length]: 2 ] },
          { long_name: 'Provincia di Varese',
            short_name: 'VA',
            types: [ 'administrative_area_level_2', 'political', [length]: 2 ] },
          { long_name: 'Lombardia',
            short_name: 'Lombardia',
            types: [ 'administrative_area_level_1', 'political', [length]: 2 ] },
          { long_name: 'Italia',
            short_name: 'IT',
            types: [ 'country', 'political', [length]: 2 ] },
          { long_name: '21017',
            short_name: '21017',
            types: [ 'postal_code', [length]: 1 ] },
          [length]: 6 ],
       formatted_address: '21017 Samarate VA, Italia',
       geometry: 
        { bounds: 
           { northeast: { lat: 45.6430867, lng: 8.8042525 },
             southwest: { lat: 45.6027756, lng: 8.7624716 } },
          location: { lat: 45.6260364, lng: 8.7870324 },
          location_type: 'APPROXIMATE',
          viewport: 
           { northeast: { lat: 45.6430867, lng: 8.8042525 },
             southwest: { lat: 45.6027756, lng: 8.7624716 } } },
       place_id: 'ChIJkVjwFxOKhkcRbfhmH_LQCJw',
       types: [ 'locality', 'political', [length]: 2 ] },
     [length]: 1 ],
  status: 'OK' }
